/* Mobile Development Project
   Bruna Heleno 3009733
 */
package com.example.brunaheleno_3009733_mdproject.database

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

//this class represent the database, table and fields that are gonna be created to make CRUD operations using the FileRepository.kt
class Database(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
    override fun onCreate(db: SQLiteDatabase?) {
        db?.execSQL(CREATE_TABLE)
    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        db?.execSQL("DROP TABLE IF EXISTS $TABLE_NAME")
        onCreate(db)
    }

    companion object{
        const val DATABASE_NAME = "stockpile.db"
        const val DATABASE_VERSION = 1
        const val TABLE_NAME = "StockPile_files"
        const val ID = "id" //unique, generated by system - autoincrement
        const val TITLE = "title" //input by user
        const val CATEGORY = "category" //input by user
        const val URI = "uri" //location of the file, generated by system
        const val TIMESTAMP = "timestamp" //time of the file, from system

        const val CREATE_TABLE= """
            CREATE TABLE $TABLE_NAME(
                $ID INTEGER PRIMARY KEY AUTOINCREMENT,
                $TITLE TEXT NOT NULL,
                $CATEGORY TEXT NOT NULL,
                $URI TEXT NOT NULL,
                $TIMESTAMP INTEGER
            );
            """
    }
}